Implementation of sendTempPacket and sendVoltagePacket
LonghornRacingElectric/hvc-firmware-2024 pull request #1
Opened 2023-11-13 19:41 UTC by Rolandw31

2023-11-15 04:04 UTC, matt-mekha commented on Core/Src/cells.cpp
> +    for(int i = offset ; i < (offset + 4) ; i++) {
change this to `i=0; i<4`

2023-11-15 04:07 UTC, matt-mekha requested changes
Overall looks good, some minor things to change

2023-11-15 04:07 UTC, matt-mekha commented on Core/Src/cells.cpp
> +    for(int i = offset ; i < (offset + 4) ; i++) {
change this to `i=0; i<4`

2023-11-15 04:07 UTC, matt-mekha commented on Core/Src/cells.cpp
> +        voltages[i] = byte1;
`i*2`

2023-11-15 04:07 UTC, matt-mekha commented on Core/Src/cells.cpp
> +        auto value = (uint16_t) (voltageData[i] / 0.001f);
incorporate the offset here instead of in the for loop

2023-11-15 04:07 UTC, matt-mekha commented on Core/Src/contactors.cpp
> +    HAL_GPIO_WritePin(Close_HV__SignalC5_GPIO_Port, Close_HV__SignalC5_Pin, (GPIO_PinState) on);
why are there two pins? what's the difference?

2023-11-15 04:07 UTC, matt-mekha commented on Core/Src/imd.cpp
> +    if(HAL_GPIO_ReadPin(IMD_Data_GPIO_Port, IMD_Data_Pin)) {
make one-liner with `HAL_GPIO_ReadPin(...) == GPIO_PIN_SET`

2023-11-15 15:18 UTC, Rolandw31 commented on Core/Src/cells.cpp
> +    for(int i = offset ; i < (offset + 4) ; i++) {
changes made

2023-11-15 15:19 UTC, Rolandw31 commented on Core/Src/cells.cpp
> +        voltages[i] = byte1;
changes made

2023-11-15 21:50 UTC, Rolandw31 commented on Core/Src/contactors.cpp
> +    HAL_GPIO_WritePin(Close_HV__SignalC5_GPIO_Port, Close_HV__SignalC5_Pin, (GPIO_PinState) on);
There is a positive and negative contactor that we are controlling, the port/pin names need some renaming I think.

2023-11-15 21:50 UTC, Rolandw31 commented on Core/Src/cells.cpp
> +        auto value = (uint16_t) (voltageData[i] / 0.001f);
changes made

2023-11-26 21:44 UTC, matt-mekha approved these changes

2023-11-26 21:44 UTC, merged